---

ansible_connection: ansible.netcommon.httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: yes
ansible_httpapi_validate_certs: no
ansible_network_os: cisco.dcnm.dcnm
ansible_user: admin
ansible_httpapi_pass: Nexusdashboard123!

fabric:
  name: MSD

vrfs:
  - vrf_name: AnsibleVRF
    vrf_id: 50001
    vlan_id: 2001
    attach:
#      - ip_address: 10.3.8.13
#      - ip_address: 10.3.8.18

networks:
  - net_name: AnsibleNet1
    vrf_name: AnsibleVRF
    net_id: 30012
    vlan_id: 2312
    vlan_name: AnsibleNet1
    gw_ip_subnet: "172.16.1.1/24"
    mtu_l3intf: 9216
#    attach:
#      - ip_address: 10.3.8.13
#        ports:
#          - Ethernet1/7
#      - ip_address: 10.3.8.14
#        ports: []
#      - ip_address: 10.3.8.18
#        ports:
#          - Ethernet1/7
  - net_name: AnsibleNet2
    vrf_name: AnsibleVRF
    net_id: 30013
    vlan_id: 2313
    vlan_name: AnsibleNet2
    gw_ip_subnet: "172.16.2.1/24"
    mtu_l3intf: 9216
#    attach:
#      - ip_address: 10.3.8.13
#        ports:
#          - Ethernet1/8
#      - ip_address: 10.3.8.14
#        ports: []
#      - ip_address: 10.3.8.18
#        ports:
#          - Ethernet1/8

